### ISSUE TITLE
getting rid of '<unk>' token in the output.

### ISSUE THREAD

**Issue by kr-sundaram** [bentrevett/pytorch-seq2seq#103]
Thank you very much for the tutorials. Helping a lot! In the tutorial of Attention is All You Need
 (tutorial 6), when tried to translate a sentence that comprises tokens not present in the dictionary, the sentence is being translated but <unk> token is coming in the output (as shown in attached image) for those input tokens. How to solve this issue? Is there any work-around?

![issue](https://user-images.githubusercontent.com/49531274/80350019-66c32080-8870-11ea-99c9-32ab5accb9c2.PNG)

**Comment by mmcux** [comment]
It is defined that only tokens which appears at least two times should be included in the vocabulary.
I guess the token 'seilbrücke' only appears once in the training set and therefore is not in the vocabulary. 
It will be then replaced by <unknown>. So the input is already <unknown> instead of 'seilbrücke' and the model predicts "correctly" <unknown> as the last word.

You could change:  min_freq = 1
```python
SRC.build_vocab(train_data, min_freq = 1)
TRG.build_vocab(train_data, min_freq = 1)
````

when building the vocabulary and try if the model can predict the right word.

**Comment by kr-sundaram** [comment]
Thanks for your reply.
