### ISSUE TITLE
Tutorial 6: use of <sos> token

### ISSUE THREAD

**Issue by brand17** [bentrevett/pytorch-seq2seq#107]
Is this token necessary in transformer model ? I mean that all tokens are passed through positional encoding layer. So the first token is already marked.

**Comment by bentrevett** [comment]
For all of the tutorials the source sequence doesn't need an `<sos>` token at all but I've left it in since it does not change the results at all - the network just learns to ignore it anyway. 

The target sequence still needs an `<sos>` token though as the first actual token you want the decoder to predict needs to be conditioned on the encoded sequence and some input (the `<sos>` token).

**Comment by brand17** [comment]
Yes, agree. Thanks for tutorial
