### ISSUE TITLE
Question about beam search using convolution and transformer

### ISSUE THREAD

**Issue by dksifoua** [bentrevett/pytorch-seq2seq#141]
Hi @bentrevett and thank you for these great tutorials,

When I evaluated recurrent models with different beam sizes, I got increased BLEU scores as beam sizes increased.

But when I evaluated convolution and transformer models with different beam sizes, I got the same BLEU scores.

```python
# For BiGRU
BLEU-4: 20.742% with beam_size=1 on validation data
BLEU-4: 21.143% with beam_size=1 on test data
BLEU-4: 21.212% with beam_size=3 on validation data
BLEU-4: 22.840% with beam_size=3 on test data
BLEU-4: 22.081% with beam_size=5 on validation data
BLEU-4: 22.797% with beam_size=5 on test data

# For Badhanau Attention
BLEU-4: 24.894% with beam_size=1 on validation data
BLEU-4: 24.983% with beam_size=1 on test data
BLEU-4: 25.701% with beam_size=3 on validation data
BLEU-4: 26.597% with beam_size=3 on test data
BLEU-4: 25.770% with beam_size=5 on validation data
BLEU-4: 26.105% with beam_size=5 on test data

# For Luong Attention
BLEU-4: 27.215% with beam_size=1 on validation data
BLEU-4: 28.706% with beam_size=1 on test data
BLEU-4: 29.321% with beam_size=3 on validation data
BLEU-4: 29.918% with beam_size=3 on test data
BLEU-4: 29.525% with beam_size=5 on validation data
BLEU-4: 30.395% with beam_size=5 on test data

# For Convolution
BLEU-4: 37.069% with beam_size=1 on validation data
BLEU-4: 37.453% with beam_size=1 on test data
BLEU-4: 37.069% with beam_size=3 on validation data
BLEU-4: 37.453% with beam_size=3 on test data
BLEU-4: 37.069% with beam_size=5 on validation data
BLEU-4: 37.453% with beam_size=5 on test data

# For Transformer
BLEU-4: 35.858% with beam_size=1 on validation data
BLEU-4: 35.500% with beam_size=1 on test data
BLEU-4: 35.858% with beam_size=3 on validation data
BLEU-4: 35.500% with beam_size=3 on test data
BLEU-4: 35.858% with beam_size=5 on validation data
BLEU-4: 35.500% with beam_size=5 on test data
```

Could you have any explanation about that?

Regards,

**Comment by bentrevett** [comment]
Sorry for the delayed response @dksifoua.

I'll admit I have not experimented with beam-search as thoroughly as you have. By "beam size" here is it changing the beam width or the beam length?

There is also no guarantee that a higher beam size (width or length) will give better BLEU scores. It will increase the likelihood of your model outputting a sequence that has a higher overall probability than greedy decoding, but this does not necessarily mean that these higher probability sequences will also correlate with higher BLEU scores. 

Just because our model thinks a sequence is more likely doesn't mean it actually is more likely in reality.

**Comment by bentrevett** [comment]
Also, the fact that the convolutional and transformer models do not achieve a higher BLEU score with a higher beam size might be implying that they might be doing something similar to a beam search implicitly within the model itself and therefore it's unnecessary to explicitly perform it.

There's also an interesting post by the HuggingFace team: https://huggingface.co/blog/how-to-generate. An interesting bit from the conclusion reads: *Recently, there has been more evidence though that the apparent flaws of greedy and beam search - mainly generating repetitive word sequences - are caused by the model (especially the way the model is trained)*.

**Comment by dksifoua** [comment]
Hi @bentrevett thank you for your response.

By `beam_size` I mean the most likely **number** of hypotheses at each time step. For `beam_size=3` for example I take the top-3 probabilities at each time step.

I read the huggingface post (very interesting) but models do not generate repetitive word sequences. Indeed the generate good translations except that they stay the same regardless of the beam size.

I was wondering if this was not due to the fact that unlike reccurent models which only use the previous predicted word to predict the next at each time step, convolutional and transformer models use on the other hand all predicted words so far to predict the next word at each time step.

What do you think about that?

**Comment by bentrevett** [comment]
> By `beam_size` I mean the most likely **number** of hypotheses at each time step. For `beam_size=3` for example I take the top-3 probabilities at each time step.

Ah ok, I believe this is what I thought beam width was. You are taking the top-3 probabilities but for only one potential sequence? I believe beam search kept a few potential sequences and looked at top-N probabilities for each of them. Don't quote me on this because I'm probably wrong.

> I read the huggingface post (very interesting) but models do not generate repetitive word sequences. Indeed the generate good translations except that they stay the same regardless of the beam size.

If they stay the same regardless of the beam size then this would maybe push evidence towards the "transformers are already implicitly doing beam search" hypothesis. 

> I was wondering if this was not due to the fact that unlike reccurent models which only use the previous predicted word to predict the next at each time step, convolutional and transformer models use on the other hand all predicted words so far to predict the next word at each time step.

I am not 100% sure this is the case. Although we are only feeding the previously predicted word back to the recurrent model we are always re-using the hidden state from the previous time-step, which - in theory - shouldn't change if we feed words one at a time and keep the hidden state or just feed the entire generated sentence so far and get the final hidden state. One way to test this would be to modify `translate_sentence` in notebook 4 to have the recurrent model process the entire decoded sentence so far at each decoding step. 

I'm not sure what data you're using, but potentially Transformers might not benefit from beam search until the datasets are large enough. Transformer models are generally very data-hungry so this might be the case.

I'd also triple check your code for any bugs (if you haven't already), potentially manually stepping through the beam search decoding in the Transformer and making sure it is actually selecting the appropriate results via the beam search.

Some other papers I found whilst looking for some research on this:
- https://arxiv.org/pdf/1808.09381.pdf - looks at different types of decoding in Transformers, beam search is better than not doing beam search but other decoding methods are superior - might be worth implementing some of these, especially the "sampling" method which is also mentioned in the HuggingFace blog post as I believe that one isn't too difficult to implement.
- https://arxiv.org/pdf/2008.07772.pdf - translation with Transformers and does not mention beam search at all, implying it might not be used?
- https://arxiv.org/pdf/2004.08249.pdf - same as above
