### ISSUE TITLE
Tutorial 6: why dropout here?

### ISSUE THREAD

**Issue by xxoospring** [bentrevett/pytorch-seq2seq#142]
Hi, I don't know why apply an dropout here which not the same as the paper
```
attention = torch.softmax(energy, dim = -1)
                
#attention = [batch size, n heads, query len, key len]
                
x = torch.matmul(self.dropout(attention), V)
```

**Comment by bentrevett** [comment]
I don't think it is explicitly mentioned in the paper, but they do apply dropout directly to the attention in the official BERT code, see: https://github.com/google-research/bert/blob/master/modeling.py#L722-L724

Directly applying dropout to attention like this has been used in the majority of post-BERT Transformer models.

**Comment by xxoospring** [comment]
OK, I see. Intuitively, what's the purpose of this drop out?  what if attention drop the part that matters most?

**Comment by bentrevett** [comment]
According to: https://arxiv.org/abs/1907.11065 the purpose is to “encourage the model to utilize the full context of the input sequences rather than relying solely on a small piece of features. For example, for sentiment classification, the prediction is usually dominated by one or several emotional words, ignoring other informative patterns.”
