### ISSUE TITLE
can i get some help?thanks!

### ISSUE THREAD

**Issue by bufuchangfeng** [bentrevett/pytorch-seq2seq#144]
I write an attention(based on lstm) for nmt using own data by studying your code.but the attention weights doesn't seem normal. here is the code. Can i get some help from you?thanks very much.
[`code`](https://github.com/bufuchangfeng/DeepLearning/blob/main/neural_machine_translation/attention.ipynb)

**Comment by cgr71ii** [comment]
I'm exactly with the same problem. I wrote my own model based on the provided code of the 3rd/4th tutorial (i.e. add attention) and I'm using my own data (specifically, I'm using Tatoeba es-en from Opus). The results when checking the attention are the same that you provided. It looks like if the attention is "looking" at the last tokens. I've checked out the code ~30 times, but I don't see any problem after have solved a few mistakes...

@bufuchangfeng did you solve this problem?

**Comment by cgr71ii** [comment]
![Captura de pantalla de 2022-01-01 02-25-58](https://user-images.githubusercontent.com/16403611/147842230-dc40cfe8-faf5-4f59-938e-3b9edd1eef1e.png)

I already know what my problem was. The problem was related to the quantity of data that I was providing. It seems that if you provide too small data, the attention will not generalize well, and it seems to focus on the last tokens for some reason I don't understand. Now, with 100.000 sentences, 60/20/20 for train/dev/test, the attention seems to focus on the expected tokens.

I just leave this comment here in the case that might help someone :)
