### ISSUE TITLE
Conversational Model Created Using Pre-Trained BERT Model is Throwing Error During Training

### ISSUE THREAD

**Issue by Ninja16180** [bentrevett/pytorch-seq2seq#160]
Hi Ben,

I have been following your tutorials and it's been a great learning experience.

I am trying to create a conversational model with custom data set where 'sent1' is the first sentence and 'sent2' is the response.

I have followed your sentiment analysis specific tutorial for the same:
https://github.com/bentrevett/pytorch-sentiment-analysis/blob/master/6%20-%20Transformers%20for%20Sentiment%20Analysis.ipynb

However, I am trying to build a conversational model where both the input and output are sentences.

Data preparation for my custom dataset went well with no error but during training I got the following error:

AttributeError: 'Batch' object has no attribute 'text'

Also, I am not very sure if any modification is required in the custom 'BERTGRUSentiment' class ( I have not changed the name of the class yet as I wanted to have the first run error free) to fit to the conversation specific use case.

Please advise.

I am also sharing the link to my github repo where I have uploaded my code with the error details, for your reference:
https://github.com/Ninja16180/BERT/blob/main/Pre-Trained_BERT_Mode_Use_Case.ipynb

Thanks in advance!

**Comment by bentrevett** [comment]
Hi @Ninja16180

The `Batch` attributes are set as the names as the `Field`s. 

Here, your `Field`s are from: `data_fields = [('sent1',sent1),('sent2',sent2)]`

Therefore the `Batch` has `sent1` and `sent2` attributes and no `text` attribute.

From a quick look at your code, you will also need to edit it to reflect the seq2seq notebooks more closely as at the moment it is predicting a single class whereas you need it to predict a sequence.

**Comment by Ninja16180** [comment]
Thanks Ben for your response.

However, I am still quite not getting the issue about the Batch attribute.

I have created two Field objects: sent1 and sent2 and used them in the data_fields variable which in turn has been used to split my custom dataset:
sent1 = data.Field(...)
sent2 = data.Field(...)

data_fields = [('sent1',sent1),('sent2',sent2)]

Could you please help me to understand where exactly I need to modify my code to fix this issue?

Thanks in advance!

**Comment by bentrevett** [comment]
The `fields` argument to `TabularDataset.splits` is a list of tuples. 

Each tuple in that list is in the form of `(FIELD_NAME, FIELD_VARIABLE)`, where `FIELD_NAME` is a string and `FIELD_VARIABLE` is a `Field`. The `FIELD_VARIABLE` is what is returned when you create the `Field`, so when you do `sent1 = data.Field(...)` this creates a `FIELD_VARIABLE` called `sent1`. The `FIELD_NAME` is what your field is going to be called inside the `Batch` object. So if your `FIELD_NAME` is `abc` then you can access it by doing `batch.abc`. Here you've put your `FIELD_NAME` as `sent1`, so you can access it from the `Batch` with `batch.sent1`. This means instead of doing `model(batch.text)` you would instead do: `model(batch.sent1)`.

Let me know if this clarifies anything.

**Comment by Ninja16180** [comment]
Thanks Ben! It clarified clearly.
In your code the names of the object of Field variables were TEXT and LABEL, so in your case they were batch.text and batch.label and likewise it should be batch.sent1 and batch.sent2 respectively in my case.

Also, as you suggested I will refer your seq2seq tutorial and try to modify the code so that the embedding from the pretrained BERT model can be used there.
I will open a new issue in case I come across any error or require any guidance in doing that exercise.

Meanwhile, closing this issue.

Thanks again!
