### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by asigalov61** [bentrevett/pytorch-seq2seq#181]
@bentrevett Thank you so much for seq2seq Attention All You Need code and colab! It's totally awesome and I was able to do my project quickly and easily thanks to it :)

I actually wanted to see if you want to add user-created colabs/code to your repo?

I made custom text colabs/implementation with your code: https://github.com/asigalov61/Torah-seq2seq-PyTorch

I think it may be useful to people who want to use their own text datasets. It was not exactly straight so I have simplified it if you do not mind...

Check it out and let me know what you think, please.

And thank you again.

Alex

**Comment by bentrevett** [comment]
@asigalov61 Sorry for the late reply. Glad the notebooks helped you! 

I've been desperately needing to update these notebooks for the better part of a year now, but other things have got in the way. I plan to update these soon(ish) to use HuggingFace Datasets, etc. which should hopefully make it easier to add an example of loading custom datasets. 

I will most probably not merge your code into this repo, only because I already struggle to maintain the notebooks that are already here. However, when I do update the repo. I will add a section to the README which links to other projects and I will be sure to add yours.
