### ISSUE TITLE
multilayer decoder

### ISSUE THREAD

**Issue by he727425209** [bentrevett/pytorch-seq2seq#29]
For lesson 3, is it possible to have a tutorial for multilayer on the decoder part? I am kind of confuse on how to pass the hidden state and cell of a multilayer encoder with LSTM into a multilayer LSTM decoder

**Comment by X3N4** [comment]
Hey,
I have also used this implementation as basis for a model because it's just awesomely clear.

Referring to the 3rd notebook: First of all you don't want to squeeze the hidden state when returning it. It'll be of size [num_layers, batch_size, hidden_size].

When passing this hidden state into the attention layer, you can't repeat it src_len times. You only want to repeat the _last hidden state_ src_len times, i.e. hidden[-1].

With those two modifications it should work fine with multiple GRU layers. Using only the top hidden state is justified in [this paper](https://arxiv.org/pdf/1508.04025.pdf) by Luong et. al.

Cheers
