### ISSUE TITLE
Lesson 3  (Attention Implementation)

### ISSUE THREAD

**Issue by abhinavshaw1993** [bentrevett/pytorch-seq2seq#34]
Thanks for the great tutorials, this has really helped me understand lot of things in detail.

In the Encoder you put the hidden layer through FC layer with tanh activation. Is this expected behavior? In the paper I could see this is done to get the initial hidden state of the Decoder. But if you do this in the Encoder, you'll be calculating the energy in the attention layer in a different way than done in the paper. I might be wrong, any elaboration here will be really helpful. 

Thanks in advance
AB

**Comment by bentrevett** [comment]
> In the Encoder you put the hidden layer through FC layer with tanh activation. Is this expected behavior? In the paper I could see this is done to get the initial hidden state of the Decoder.

Yes, this is expected. It's pretty hidden within the paper itself. The line in question is appendix 2.2 on page 13:  "The initial hidden state s_0 is computed by s_0 = tanh(W_s h_1_bck)". I deviate from the paper a little as they claim to only use the final backward LSTM hidden state, whereas I use the final backward and final forward LSTM hidden states. I also use a linear layer with a bias instead of just doing a matrix multiplication,  so mine is: s_0 = tanh(W_s [h_1_bck; h_T_fwd] + b_s). 

This is only used to calculate the initial hidden state of the decoder, s_0, which is denoted by `hidden` in the `Encoder` module. The attention is done over all of the hidden states output by the `Encoder`, denoted by `outputs` and H. These `outputs` have not been through the linear layer with tanh activation, which is consistent with the paper.

I hope that clarifies things, but if not then I can go through sections in more detail.

**Comment by abhinavshaw1993** [comment]
Thank you so much. It clarifies everything. Attention doesn't use the hidden state in any way. And you are not putting the `Encoder` outputs through tanh non linearity. 

I am truly grateful for this tutorial. Not having done any course in NLP I was struggling with attention and sequence modeling in general. Your tutorial is very comprehensive and different from other blog posts that I have seen, as it actually shows the readers how to decode and generate predictions.  

Great work! Can I add you on linkedin? I couldn't find a link to your profile in your website. 

Best
AB

**Comment by bentrevett** [comment]
> Can I add you on linkedin? I couldn't find a link to your profile in your website.

Of course! I'll admit I don't use it much but the link to my profile is: https://www.linkedin.com/in/ben-trevett-b58025b4/

I should add it to my website though, thanks for reminding me!
