### ISSUE TITLE
arguments are located on different GPUs

### ISSUE THREAD

**Issue by SoheilZabihi** [bentrevett/pytorch-seq2seq#4]
Thank you for your helpful tutorial.
I tried to use multi GPU to run Seq2Seq model which is implemented in the first tutorial by adding following lines to code
`if torch.cuda.device_count() > 1:`
    `model = nn.DataParallel(model, device_ids=[0, 1], dim=1)`
But I faced with this error  "arguments are located on different GPUs", which is because of the Fully Connected layer in the Decoder class.
Did you ever run this model with multi GPU?
or do you think this is PyTorch bug?

**Comment by bentrevett** [comment]
This is probably an issue with my code, however as I only own a single GPU myself, I'm not sure how I'll be able to debug this.

**Comment by gkjegan** [comment]
@SoZab Did you able to run this code in multiple GPU? I run for 1 million text and its pretty slow and wanted to run with multiple GPU approach

**Comment by Kristin33** [comment]
Oh yeah I encountered same problem this week! (Which notebook are you on? I was using notebook 6) 

It's because the input tensor and the model tensor are not on the same GPU. In the code, there are tensors like masks that's initiated in the init part of the module, and then send to the GPU immediately. This kind of model tensor stays in cuda:0 with the main model, while input is on other GPUs so computations can't be done. It's also simple to fix it: don't call .to(device) at the init part of the module, but send tensor to GPU inside the forward function where we can make sure it's the same device as the input, as DataParallel is only splitting the work in forward function. 

![image](https://user-images.githubusercontent.com/31784445/87128907-0bc39600-c2c3-11ea-8a59-95bec2c37df0.png)

**Comment by swinalmeida** [comment]
Hey @Kristin33 Can you please help me with the multi gpu implementation.
