### ISSUE TITLE
lesson1，calculate the loss between trg and ouput when traning

### ISSUE THREAD

**Issue by zhao1402072392** [bentrevett/pytorch-seq2seq#46]
thanks for your tutorial ,it's really helpful!
but i find some wrong in lesson1，calculate the loss between trg and ouput when traning:
because you add `<sos>` and `<eos>` to trg,i think that you should calculate the loss between the data in the two blue box in the pic,so it should be trg[1:] and output[:-1],right?^-^
![fullsizerender](https://user-images.githubusercontent.com/26305182/66447078-b29eab80-ea7f-11e9-8c31-57aa9da854aa.jpg)

**Comment by bentrevett** [comment]
OK, there was a bug here, not exactly the one you mentioned - but a closely related one.

The issue was that the `<eos>` token should not be put into the decoder in the first place. Thus, the bug is that the decoding loop should to go `max_len - 1` and not to `max_len`. This means we have something like:

![](https://i.imgur.com/JgRVBH3.jpg)

Note that we still slice from `[1:]`. 

The zero at the start of `out` is due to us creating the `outputs` tensor to store all the translations. It is initialized as all zeros and we start filling it from element 1, and not element 0. Thus, we need to slice off the zero from the `outputs` and the `<sos>` token from `trg`.

Thanks for spotting the bug though!

**Comment by zhao1402072392** [comment]
Thank you very much !!got it, thanks again^-^

**Comment by zhao1402072392** [comment]
Thanks for your mention, you mean here should be max_len-1,right?(in the class Seq2Seq)




------------------ 原始邮件 ------------------
发件人: "Ben Trevett"<notifications@github.com>;
发送时间: 2019年10月9日(星期三) 晚上8:33
收件人: "bentrevett/pytorch-seq2seq"<pytorch-seq2seq@noreply.github.com>;
抄送: "赵家胥"<1402072392@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [bentrevett/pytorch-seq2seq] lesson1，calculate the loss between trg and ouput when traning (#46)




OK, there was a bug here, not exactly the one you mentioned - but a closely related one.
 
The issue was that the <eos> token should not be put into the decoder in the first place. Thus, the bug is that the decoding loop should to go max_len - 1 and not to max_len. This means we have something like:
 

 
Note that we still slice from [1:].
 
The zero at the start of out is due to us creating the outputs tensor to store all the translations. It is initialized as all zeros and we start filling it from element 1, and not element 0. Thus, we need to slice off the zero from the outputs and the <sos> token from trg.
 
Thanks for spotting the bug though!

**Comment by bentrevett** [comment]
No, ignore all of that. I originally thought there *was* a bug, but there isn't. Oops.

The loop still needs to go from `1` to `max_len`.

**Comment by zhao1402072392** [comment]
okay,thank you very much ^_^,by the way,are you a doctor or professor majoring in NLP?




------------------ 原始邮件 ------------------
发件人: "Ben Trevett"<notifications@github.com>;
发送时间: 2019年10月11日(星期五) 晚上9:14
收件人: "bentrevett/pytorch-seq2seq"<pytorch-seq2seq@noreply.github.com>;
抄送: "赵家胥"<1402072392@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [bentrevett/pytorch-seq2seq] lesson1，calculate the loss between trg and ouput when traning (#46)




No, ignore all of that. I originally thought there was a bug, but there isn't. Oops.
 
The loop still needs to go from 1 to max_len.

**Comment by bentrevett** [comment]
No worries. Nope, just a student with an interest in NLP.
