### ISSUE TITLE
How to generate new unseen translations

### ISSUE THREAD

**Issue by fcarichon** [bentrevett/pytorch-seq2seq#5]
Hi,

Once again Thanks for the tutorial. Very Helpful.
I have a question on your tutorial about how do you get an actual translation when you have "finish" to train your model?
For example if I want to input a new unseen german phrase like "das ist das Ergebnis meines Modells.", how  can I get "This is the result of my model"?
Because the Seq2Seq model always take the real translation as an input (src and trg)? How can I do if I don't have any target? Does I have to create a random one that won't be used in the evaluation?
And then, how you eventually turn back the tensor that you get in output because I don't see some kind of index2word dictionary that reverse the object src.build_vocab?

Thanks a lot for your answer.

**Comment by bentrevett** [comment]
Hi,

Thanks again for the kind words.

Here is a gist where we carry out some inference using the model from the first notebook: https://gist.github.com/bentrevett/1eaf9c512733345787c7fc7272a3f8ff

The only changes we make are to the `Seq2Seq` model, where we now assume that when a `trg` of `None` is passed we are doing inference. In this case, we just set `trg` to a dummy tensor filled with `<sos>` tokens. We never actually use these tokens (as `teacher_forcing_ratio` should be zero) except for the very first input to the decoder, which should always be `<sos>`. 

I've also created the `translate_sentence` function, which will take an input string in German and handle the tokenization, numericalization, converting to tensor, feeding into the model and converting the model probabilities into predictions and then converting them into English. Hopefully this answers the second part of your question.

You may be thinking the results are unsatisfactory, and I agree. The issue is that we are using a very basic model (the model from tutorial 3 should give a lot better results) and the embedding/hidden dimension sizes I am using in these tutorials are relatively small compared to standard sizes used in research (usually hidden dimenions of >1000). I reduced the sizes so thinks didn't take ages to train and so everything fit on my GPU. 

Let me know if that answers everything.

**Comment by fcarichon** [comment]
Thanks a lot, the answer is perfectly answering to my points.
