### ISSUE TITLE
Question on Tutorial 3 (rnn output explanation)

### ISSUE THREAD

**Issue by antgr** [bentrevett/pytorch-seq2seq#51]
Hi,
the tutorial gives the following interpretation/explanation for the output of rnn :
```You can think of the third axis as being the forward and backward hidden states stacked on top of each other```
But here I would like to ask for some help. I would understand this as a concatenation rather than as stacking. Do we say the same thing with other words? 
To me stacking would be a kind of nesting for example if we had [src sent len, batch size, hid dim , num directions] instead of [src sent len, batch size, hid dim * num directions] .  Could you elaborate?
Thanks!

**Comment by bentrevett** [comment]
Yeah, concatenation would be a better term - not sure why I originally said "stacking". Must be the way I picture it. I'll look into changing it.

**Comment by antgr** [comment]
In flair (nlp library) they use the same term. For example they use the term StackedEmbeddings, where it means concatenate the embeddings, as I discovered. So it may makes sense. (But I found it a bit confusing). Thanks for the answer!

**Comment by bentrevett** [comment]
Yeah, I think because the order they are concatenated is always forward:backward I have this image in my head of the forward hidden states being "under" the backward hidden states. Concatenation is a much better term, I think calling it stacking just confuses things with multi-layer RNNs when those are actually stacked on top of each other (as they process data up the stack from the first layer to the last).

I'll change it tonight.
