### ISSUE TITLE
Why the attention is a function of encoder's output?

### ISSUE THREAD

**Issue by ziadloo** [bentrevett/pytorch-seq2seq#53]
In the 3rd Jupyter notebook, the attention layer is a function of the encoder's output and decoder's hidden state. This is in the case that in the reference article and also the in the text explanation of the same Jupyter notebook, it is stated that the attention is a function of both encoder's and decoder's hidden state:

> Next up is the attention layer. This will take in the previous hidden state of the decoder, $s_{t-1}$, and all of the stacked forward and backward hidden states from the encoder, $H$.

Is it ok to use the encoder's output instead of its hidden state? If it is, why not use the decoder's output instead of its hidden state?

**Comment by bentrevett** [comment]
In the tutorials, we refer to *all* of the encoder's hidden states as the encoder's output. We say *hidden state* when we are referring to a single hidden state, we say *outputs* when we are referring to all of the hidden states, one per time-step.

This naming was done to be consistent with the PyTorch documentation, see: https://pytorch.org/docs/stable/nn.html#torch.nn.GRU

They name the two outputs of the GRU `outputs` and `h_n`. `outputs` is a tensor containing the hidden state for every time-step over the input sequence and `h_n` is just the final hidden state.

You want to use the encoder's output (all of the hidden states) as you're trying to find which of the states (i.e. which word in the input sentence) you should be paying attention to. If you are simply feeding the final hidden state you have no sequence to pay attention over. 

We use the decoder's hidden state (from the current time-step) instead of the decoder's output (from all time-steps) as we are hoping that the hidden state has a summary of the sentence it has output so far, which we can then use (with the encoder outputs and attention mechanisms) to predict the next word in the sequence.

Surely it's more beneficial to use all of the decoder hidden states and not just the current one? I'm sure it would be and I believe there are some *self-attention* recurrent models that do this. But I wanted this notebook to simply implement the paper that introduced attention, without getting into details about self-attention, etc. 

Hope that's cleared some stuff up. Let me know if not.

**Comment by ziadloo** [comment]
Thank you for the time you've spent to write this explanation.

I didn't know that the hidden state is the last output. I thought that `outputs=[f(h_t)]` (where `[]` means concatenating all the time-step). In other words, I thought there's a layer over the hidden states and that one's results are the outputs.

On the topic of why one should not use decoder's outputs (instead of its hidden state) as a whole, in that case, the attention output could not be fed back into the next time-step. I mean if you are using the outputs of the decoder, you've lost your chance to feed back the result of the attention layer into the input.

Thanks again.
