### ISSUE TITLE
A little question about pytorch-seq2seq/3 - Neural Machine Translation by Jointly Learning to Align and Translate.ipynb

### ISSUE THREAD

**Issue by guoxiaojun1999** [bentrevett/pytorch-seq2seq#55]
In the function **_forward_** of module _**Encoder**_, does variable _**outputs**_ mean all of the stacked forward and backward hidden states from the encoder and variable _**hidden**_ mean the context vector? I'm confused because the literal meaning of these two variables differs from what they actually stand for.
Thanks a lot.

**Comment by guoxiaojun1999** [comment]
> In the function **_forward_** of module _**Encoder**_, does variable _**outputs**_ mean all of the stacked forward and backward hidden states from the encoder and variable _**hidden**_ mean the context vector? I'm confused because the literal meaning of these two variables differs from what they actually stand for.
> Thanks a lot.

Oops! I think I know the meanings. There is no contradiction.

**Comment by bentrevett** [comment]
Yep, you're correct. I know these variable names aren't the most intuitive but the PyTorch official documentation refers to them as `output` and `h_n`. 

I preferred `outputs` over `output` as I wanted it to be plural to highlight that this comes from more than one hidden state. `hidden` over `h_n` because it's just more readable.
