### ISSUE TITLE
a mini spelling error

### ISSUE THREAD

**Issue by zhiyiZeng** [bentrevett/pytorch-seq2seq#86]
Hello, in the 6th chapter, there is one sentence as following:
> However, each context vector here as seen all tokens at all positions within the input sequence.

It seems "as" should be "has".

I've followed your tutorials several days ago, which should be one of the most elegant and concise tutorials referring to seq2seq models. I've been learning deep learning, mostly NLP, but the progress in replicating models from papers is way from satisfying. I'm curious about how you can replicate those models so elegant without any problem to read ? Is it convenient for you to give me some tips about how to learn NLP ?

Thanks in advance!
Best wishes.

**Comment by bentrevett** [comment]
Thanks for letting me know, let me know if you spot any more.

I definitely think implementing papers is the best way to learn NLP techniques. I usually start by reading the paper and then trying to implement them myself and then searching online for other implementations to double check if what I'm doing is correct and I've properly understood the paper. It usually takes a long time, but you learn a lot by doing it. As you implement papers you slowly understand more and then have to go back and edit your previous implementations with what you've learned to improve them. 

Writing/explaning how each concept works also helps as it ensures you truly understand what's going on. If I can't write a decent explanation of what is going on then I most probably don't really understand it myself, and it helps me find gaps in my knowledge.

Learning all of these techniques takes time, and is frustrating at first because there's a lot of concepts you don't understand - but as you slowly learn each one, you'll build up the knowledge that helps you with further techniques and implementations.

[This](https://www.morganclaypool.com/doi/abs/10.2200/S00762ED1V01Y201703HLT037) book was one I read early on and it helped clarify a lot of concepts. I would definitely recommend it. 

There's no quick and easy way to learn these techniques - it just takes time. If you put the time in, you'll definitely be able to understand them.

Hope this advice is useful in some way, and thanks again for the kind words.

**Comment by zhiyiZeng** [comment]
Thanks for the kind advice. It means a lot to me. Hope one day I will be good enough to discuss advanced techniques with you. Cheers~
