### ISSUE TITLE
Discussion about reversing the order of the source sentence

### ISSUE THREAD

**Issue by littleflow3r** [bentrevett/pytorch-seq2seq#9]
Hi, again thanks for the nice tutorial.

I run the experiment with reversing the order of the source sentence as in your tutorial and using the original order. It turned out that using the original order gave better result in my data (I used Japanese-English translation data http://cs.stanford.edu/~rpryzant/jesc/).

Do you have some idea or intuition behind reversing the order of the sentence? I read the original paper and it seems that it relates to the problem of 'minimal time lag'.  But, I am not sure why it doesn't work on my data.

Thanks.

**Comment by bentrevett** [comment]
My only intuition is the same as the paper, that is, reversing the order of the input sentence reduces the path length of information between the beginning of the two sentences.

If you note, tutorials 2 and 3 do not reverse their input sentences. Potentially because their improved architecture/models were able to cope with this longer path of information? Although that is just a guess and I don't think I tried those models with reversed input sentences.

I don't believe I've seen a study on what languages benefit from reversing input sentences, it's definitely something that could do with researching. 

Have you tried comparing the reversed and original results across a few random seeds to make sure you consistently get better results for the original order?

**Comment by littleflow3r** [comment]
I just realised that in my data (Japanese-English), the last word is the verb, which is quite important information from the sequence. Probably that's why reversing the order does not really work since the important information would be further separated then. 

>Have you tried comparing the reversed and original results across a few random seeds to make sure you consistently get better results for the original order?
Will do!

Thanks again!
